name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      BOT_TOKEN:
        description: 'Your Telegram bot token'
        required: true
        type: string
      OWNER_ID:
        description: 'Your Telegram ID'
        required: true
        type: string
      DATABASE_URL:
        description: 'MongoDB connection string'
        required: true
        type: string
      TELEGRAM_API:
        description: 'Telegram API ID (from my.telegram.org)'
        required: true
        type: string
      TELEGRAM_HASH:
        description: 'Telegram API hash (from my.telegram.org)'
        required: true
        type: string
      HEROKU_APP_NAME:
        description: 'Name of your Heroku app'
        required: true
        type: string
      HEROKU_EMAIL:
        description: 'Email address associated with your Heroku account'
        required: true
        type: string
      HEROKU_API_KEY:
        description: 'API key from your Heroku account'
        required: true
        type: string
      HEROKU_TEAM_NAME:
        description: 'Heroku team name (optional)'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "BOT_TOKEN=${{ github.event.inputs.BOT_TOKEN }}" >> $GITHUB_ENV
          echo "OWNER_ID=${{ github.event.inputs.OWNER_ID }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ github.event.inputs.DATABASE_URL }}" >> $GITHUB_ENV
          echo "TELEGRAM_API=${{ github.event.inputs.TELEGRAM_API }}" >> $GITHUB_ENV
          echo "TELEGRAM_HASH=${{ github.event.inputs.TELEGRAM_HASH }}" >> $GITHUB_ENV

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ github.event.inputs.HEROKU_API_KEY }}
          heroku_app_name: ${{ github.event.inputs.HEROKU_APP_NAME }}
          heroku_email: ${{ github.event.inputs.HEROKU_EMAIL }}
          team: ${{ github.event.inputs.HEROKU_TEAM_NAME }}
        env:
          BOT_TOKEN: ${{ github.event.inputs.BOT_TOKEN }}
          OWNER_ID: ${{ github.event.inputs.OWNER_ID }}
          DATABASE_URL: ${{ github.event.inputs.DATABASE_URL }}
          TELEGRAM_API: ${{ github.event.inputs.TELEGRAM_API }}
          TELEGRAM_HASH: ${{ github.event.inputs.TELEGRAM_HASH }}
